require('dotenv').config();
const oracledb = require('oracledb');
const db = require('./src/config/db');

async function run() {
  console.log('Running attendance migration...');
  const conn = await db.getConnection();
  try {
    // 1. Drop attendance_records constraints/table
    try {
      console.log('Dropping existing table attendance_records...');
      await conn.execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE attendance_records CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;");
    } catch (e) {
      console.log('No table found or error dropping:', e.message);
    }

    // 2. Recreate attendance_records table
    console.log('Creating table attendance_records with lecture_number column...');
    const createTableSql = `
      CREATE TABLE attendance_records (
        attendance_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        enrollment_id NUMBER NOT NULL,
        lecture_number NUMBER NOT NULL CHECK (lecture_number BETWEEN 1 AND 16),
        attendance_date DATE DEFAULT SYSDATE NOT NULL,
        status VARCHAR2(20) DEFAULT 'Present' NOT NULL CHECK (status IN ('Present','Absent','Late')),
        CONSTRAINT fk_attendance_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id) ON DELETE CASCADE,
        CONSTRAINT uq_attendance_enroll_lecture UNIQUE (enrollment_id, lecture_number)
      )
    `;
    await conn.execute(createTableSql);

    // 3. Create index
    console.log('Creating index on attendance_records...');
    await conn.execute(`CREATE INDEX idx_attendance_student_date ON attendance_records(enrollment_id, attendance_date)`);

    // 4. Recompile MarkAttendance stored procedure
    console.log('Recompiling MarkAttendance stored procedure...');
    const procedureSql = `
      CREATE OR REPLACE PROCEDURE MarkAttendance(
        p_section_id IN NUMBER,
        p_lecture_number IN NUMBER,
        p_json IN CLOB
      ) AS
      BEGIN
        IF p_section_id IS NULL OR p_lecture_number IS NULL OR p_json IS NULL THEN
          RAISE_APPLICATION_ERROR(-20001, 'Section ID, lecture number, and attendance payload are required.');
        END IF;

        MERGE INTO attendance_records ar
        USING (
          SELECT e.enrollment_id, jt.student_id, jt.present
            FROM enrollments e
            JOIN JSON_TABLE(p_json, '$[*]' COLUMNS (
              student_id NUMBER PATH '$.studentID',
              present VARCHAR2(5) PATH '$.present'
            )) jt ON e.student_id = jt.student_id
           WHERE e.section_id = p_section_id
        ) src
        ON (ar.enrollment_id = src.enrollment_id AND ar.lecture_number = p_lecture_number)
        WHEN MATCHED THEN UPDATE SET ar.status = CASE WHEN src.present = 'true' THEN 'Present' ELSE 'Absent' END, ar.attendance_date = SYSDATE
        WHEN NOT MATCHED THEN INSERT (attendance_id, enrollment_id, lecture_number, attendance_date, status)
          VALUES (attendance_records_seq.NEXTVAL, src.enrollment_id, p_lecture_number, SYSDATE, CASE WHEN src.present = 'true' THEN 'Present' ELSE 'Absent' END);

        COMMIT;
      EXCEPTION
        WHEN OTHERS THEN
          ROLLBACK;
          RAISE_APPLICATION_ERROR(-20020, 'MarkAttendance failed: ' || SQLERRM);
      END;
    `;
    await conn.execute(procedureSql);

    // 4b. Recompile AuthenticateUser stored procedure
    console.log('Recompiling AuthenticateUser stored procedure...');
    const authenticateUserSql = `
      CREATE OR REPLACE PROCEDURE AuthenticateUser(
        p_email IN VARCHAR2,
        p_password IN VARCHAR2,
        p_role OUT VARCHAR2,
        p_refid OUT VARCHAR2
      ) AS
      BEGIN
        SELECT role, reference_id
          INTO p_role, p_refid
          FROM user_accounts
         WHERE LOWER(TRIM(email)) = LOWER(TRIM(p_email))
           AND (
             NVL(TRIM(plain_password),'') = TRIM(p_password)
             OR NVL(TRIM(password_hash),'') = TRIM(p_password)
           );
      EXCEPTION
        WHEN NO_DATA_FOUND THEN
          RAISE_APPLICATION_ERROR(-20001, 'Invalid email or password');
      END;
    `;
    await conn.execute(authenticateUserSql);

    // 4c. Recompile SearchCourses stored procedure
    console.log('Recompiling SearchCourses stored procedure...');
    const searchCoursesSql = `
      CREATE OR REPLACE PROCEDURE SearchCourses(
        p_department_id IN NUMBER,
        p_keyword IN VARCHAR2,
        p_cursor OUT SYS_REFCURSOR
      ) AS
        l_sql VARCHAR2(4000);
      BEGIN
        l_sql := 'SELECT course_id, course_code, course_title, credit_hours FROM courses WHERE 1=1';
        IF p_department_id IS NOT NULL THEN
          l_sql := l_sql || ' AND department_id = :dept';
        END IF;
        IF p_keyword IS NOT NULL THEN
          l_sql := l_sql || ' AND (LOWER(course_title) LIKE LOWER(:keyword) OR LOWER(course_code) LIKE LOWER(:keyword))';
        END IF;

        IF p_department_id IS NOT NULL AND p_keyword IS NOT NULL THEN
          OPEN p_cursor FOR l_sql USING p_department_id, '%' || p_keyword || '%', '%' || p_keyword || '%';
        ELSIF p_department_id IS NOT NULL THEN
          OPEN p_cursor FOR l_sql USING p_department_id;
        ELSIF p_keyword IS NOT NULL THEN
          OPEN p_cursor FOR l_sql USING '%' || p_keyword || '%', '%' || p_keyword || '%';
        ELSE
          OPEN p_cursor FOR l_sql;
        END IF;
      END;
    `;
    await conn.execute(searchCoursesSql);

    // 5. Grant permissions
    console.log('Re-granting execute permissions on procedures...');
    await conn.execute(`GRANT EXECUTE ON MarkAttendance TO db_faculty, db_admin`);
    await conn.execute(`GRANT EXECUTE ON AuthenticateUser TO db_student, db_faculty, db_admin, db_finance`);
    await conn.execute(`GRANT EXECUTE ON SearchCourses TO db_student, db_faculty, db_admin, db_finance`);

    // 6. Seed dummy attendance data
    console.log('Seeding dummy attendance records...');
    const seedSql = `
      INSERT INTO attendance_records(enrollment_id, lecture_number, attendance_date, status)
      SELECT e.enrollment_id, d.lec_num, d.att_date, CASE WHEN MOD(ROWNUM,5)=0 THEN 'Absent' ELSE 'Present' END
      FROM enrollments e
      JOIN (
        SELECT 1 AS lec_num, TO_DATE('2025-09-01','YYYY-MM-DD') AS att_date FROM dual UNION ALL
        SELECT 2 AS lec_num, TO_DATE('2025-09-03','YYYY-MM-DD') FROM dual UNION ALL
        SELECT 3 AS lec_num, TO_DATE('2025-09-05','YYYY-MM-DD') FROM dual
      ) d ON 1=1
      WHERE e.student_id = (SELECT student_id FROM students WHERE email='student1@hitec.edu.pk')
    `;
    await conn.execute(seedSql);

    await conn.commit();
    console.log('Migration successfully completed!');
  } catch (err) {
    console.error('Migration failed:', err);
    try {
      await conn.rollback();
    } catch (e) {
      console.error('Rollback failed:', e);
    }
  } finally {
    try {
      await conn.close();
    } catch (e) {
      console.error(e);
    }
    process.exit(0);
  }
}

run();
