SET DEFINE OFF;

CREATE TABLE departments (
  dept_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  dept_name VARCHAR2(100) NOT NULL UNIQUE,
  dept_code VARCHAR2(20) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE programs (
  program_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  program_name VARCHAR2(150) NOT NULL,
  department_id NUMBER NOT NULL,
  duration_semesters NUMBER DEFAULT 8 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_program_dept FOREIGN KEY (department_id) REFERENCES departments(dept_id) ON DELETE CASCADE
);

CREATE TABLE user_accounts (
  user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  email VARCHAR2(255) NOT NULL UNIQUE,
  password_hash VARCHAR2(4000) NOT NULL,
  role VARCHAR2(20) NOT NULL CHECK (role IN ('Admin','Student','Faculty','Finance')),
  reference_id NUMBER,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE students (
  student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL UNIQUE,
  first_name VARCHAR2(100) NOT NULL,
  last_name VARCHAR2(100) NOT NULL,
  email VARCHAR2(255) NOT NULL UNIQUE,
  cnic_raw VARCHAR2(25),
  cnic_encrypted RAW(2000),
  program_id NUMBER NOT NULL,
  admission_date DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(20) DEFAULT 'Active' NOT NULL,
  CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES user_accounts(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_student_program FOREIGN KEY (program_id) REFERENCES programs(program_id) ON DELETE SET NULL
);

CREATE TABLE faculty (
  faculty_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL UNIQUE,
  first_name VARCHAR2(100) NOT NULL,
  last_name VARCHAR2(100) NOT NULL,
  email VARCHAR2(255) NOT NULL UNIQUE,
  department_id NUMBER NOT NULL,
  bank_account_raw VARCHAR2(100),
  bank_account_encrypted RAW(2000),
  hire_date DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(20) DEFAULT 'Active' NOT NULL,
  CONSTRAINT fk_faculty_user FOREIGN KEY (user_id) REFERENCES user_accounts(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_faculty_dept FOREIGN KEY (department_id) REFERENCES departments(dept_id) ON DELETE SET NULL
);

CREATE TABLE staff (
  staff_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER UNIQUE,
  full_name VARCHAR2(200) NOT NULL,
  department_id NUMBER NOT NULL,
  role VARCHAR2(100) NOT NULL,
  hire_date DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_staff_user FOREIGN KEY (user_id) REFERENCES user_accounts(user_id) ON DELETE SET NULL,
  CONSTRAINT fk_staff_dept FOREIGN KEY (department_id) REFERENCES departments(dept_id) ON DELETE SET NULL
);

CREATE TABLE courses (
  course_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  course_code VARCHAR2(20) NOT NULL UNIQUE,
  course_title VARCHAR2(200) NOT NULL,
  credit_hours NUMBER NOT NULL CHECK (credit_hours BETWEEN 1 AND 5),
  department_id NUMBER NOT NULL,
  prerequisite_course_id NUMBER,
  description VARCHAR2(2000),
  CONSTRAINT fk_course_dept FOREIGN KEY (department_id) REFERENCES departments(dept_id) ON DELETE SET NULL,
  CONSTRAINT fk_course_prereq FOREIGN KEY (prerequisite_course_id) REFERENCES courses(course_id) ON DELETE SET NULL
);

CREATE TABLE sections (
  section_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  course_id NUMBER NOT NULL,
  faculty_id NUMBER NOT NULL,
  semester VARCHAR2(20) NOT NULL,
  year NUMBER NOT NULL,
  capacity NUMBER NOT NULL CHECK (capacity > 0),
  available_seats NUMBER NOT NULL,
  schedule VARCHAR2(200),
  room VARCHAR2(100),
  CONSTRAINT fk_section_course FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE,
  CONSTRAINT fk_section_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(faculty_id) ON DELETE SET NULL,
  CONSTRAINT chk_available_seats CHECK (available_seats >= 0)
);

CREATE TABLE enrollments (
  enrollment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id NUMBER NOT NULL,
  section_id NUMBER NOT NULL,
  enroll_date DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(20) DEFAULT 'Enrolled' NOT NULL,
  CONSTRAINT fk_enroll_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE,
  CONSTRAINT fk_enroll_section FOREIGN KEY (section_id) REFERENCES sections(section_id) ON DELETE CASCADE,
  CONSTRAINT uq_enrollment_student_section UNIQUE (student_id, section_id)
);

CREATE TABLE grades (
  grade_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  enrollment_id NUMBER NOT NULL UNIQUE,
  grade_value VARCHAR2(2) NOT NULL,
  grade_points NUMBER NOT NULL,
  letter_grade VARCHAR2(2) NOT NULL,
  graded_on DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_grade_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id) ON DELETE CASCADE
);

CREATE TABLE attendance_records (
  attendance_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  enrollment_id NUMBER NOT NULL,
  attendance_date DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(20) DEFAULT 'Present' NOT NULL CHECK (status IN ('Present','Absent','Late')),
  CONSTRAINT fk_attendance_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(enrollment_id) ON DELETE CASCADE
);

CREATE TABLE fee_structures (
  fee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  program_id NUMBER NOT NULL,
  amount NUMBER NOT NULL CHECK (amount >= 0),
  semester VARCHAR2(20) NOT NULL,
  due_date DATE NOT NULL,
  CONSTRAINT fk_fee_program FOREIGN KEY (program_id) REFERENCES programs(program_id) ON DELETE CASCADE
);

CREATE TABLE fee_payments (
  payment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id NUMBER NOT NULL,
  amount NUMBER NOT NULL CHECK (amount >= 0),
  payment_method VARCHAR2(50) NOT NULL,
  payment_date DATE DEFAULT SYSDATE NOT NULL,
  reference VARCHAR2(200),
  bank_account_raw VARCHAR2(100),
  bank_account_encrypted RAW(2000),
  status VARCHAR2(20) DEFAULT 'Completed' NOT NULL,
  CONSTRAINT fk_payment_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE
);

CREATE TABLE library_items (
  item_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  title VARCHAR2(300) NOT NULL,
  author VARCHAR2(200) NOT NULL,
  isbn VARCHAR2(30) UNIQUE,
  item_type VARCHAR2(50) NOT NULL,
  total_copies NUMBER NOT NULL CHECK (total_copies >= 0),
  available_copies NUMBER NOT NULL CHECK (available_copies >= 0),
  publisher VARCHAR2(200),
  publish_year NUMBER,
  pages NUMBER,
  CONSTRAINT chk_copies CHECK (available_copies <= total_copies)
);

CREATE TABLE library_issues (
  issue_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  item_id NUMBER NOT NULL,
  student_id NUMBER NOT NULL,
  issue_date DATE DEFAULT SYSDATE NOT NULL,
  due_date DATE NOT NULL,
  return_date DATE,
  fine_amount NUMBER DEFAULT 0 NOT NULL,
  status VARCHAR2(20) DEFAULT 'Issued' NOT NULL,
  CONSTRAINT fk_issue_item FOREIGN KEY (item_id) REFERENCES library_items(item_id) ON DELETE CASCADE,
  CONSTRAINT fk_issue_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE
);

CREATE TABLE hostels (
  hostel_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  hostel_name VARCHAR2(150) NOT NULL UNIQUE,
  total_rooms NUMBER NOT NULL CHECK (total_rooms >= 0),
  available_rooms NUMBER NOT NULL CHECK (available_rooms >= 0)
);

CREATE TABLE hostel_allotments (
  allotment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id NUMBER NOT NULL,
  hostel_id NUMBER NOT NULL,
  room_number VARCHAR2(50) NOT NULL,
  start_date DATE DEFAULT SYSDATE NOT NULL,
  end_date DATE,
  status VARCHAR2(20) DEFAULT 'Allocated' NOT NULL,
  CONSTRAINT fk_allot_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE,
  CONSTRAINT fk_allot_hostel FOREIGN KEY (hostel_id) REFERENCES hostels(hostel_id) ON DELETE CASCADE
);

CREATE TABLE exam_schedule (
  schedule_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  course_id NUMBER NOT NULL,
  section_id NUMBER NOT NULL,
  exam_date DATE NOT NULL,
  exam_type VARCHAR2(50) NOT NULL,
  exam_room VARCHAR2(100),
  CONSTRAINT fk_exam_course FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE,
  CONSTRAINT fk_exam_section FOREIGN KEY (section_id) REFERENCES sections(section_id) ON DELETE CASCADE
);

CREATE TABLE results (
  result_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  student_id NUMBER NOT NULL,
  course_id NUMBER NOT NULL,
  semester VARCHAR2(20) NOT NULL,
  year NUMBER NOT NULL,
  gpa NUMBER(5,2),
  cgpa NUMBER(5,2),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_result_student FOREIGN KEY (student_id) REFERENCES students(student_id) ON DELETE CASCADE,
  CONSTRAINT fk_result_course FOREIGN KEY (course_id) REFERENCES courses(course_id) ON DELETE CASCADE
);

CREATE TABLE audit_log (
  audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  table_name VARCHAR2(100) NOT NULL,
  operation VARCHAR2(20) NOT NULL,
  record_id VARCHAR2(100),
  old_values CLOB,
  new_values CLOB,
  changed_by VARCHAR2(200),
  changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
